language: cpp
os: linux
dist: bionic
sudo: required
compiler: gcc

install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install cmake
  - sudo apt-get install lcov
  - sudo apt-get install libboost-dev
  - sudo ./start.sh install gtest
  - cmake .
  - make

script: true
  - build/bin/unit_test

after_success:
  - bash <(curl -s https://codecov.io/bash)