language: cpp
os: linux
sudo: required
compiler: gcc
addons:
  apt:
    packages: [lcov]
env:
  - COMPILER=g++-8

install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install g++-8
  - sudo apt-get install cmake
  - export CXX=${COMPILER}
  - ./start.sh
  - cmake .
  - make

script: true
  - build/bin/unit_test

after_success:
  - bash <(curl -s https://codecov.io/bash)